name: ESP32 Test

on: [push, workflow_dispatch]

jobs:
  esp32-test:
    runs-on: ubuntu-latest
    container: espressif/idf:latest

    strategy:
      fail-fast: false
      matrix:
        flappiness: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F"]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Install pytest and pytest-embedded plugins
      run: |
        set -e
        . $IDF_PATH/export.sh
        pip install pytest==7.0.1 \
            pytest-embedded==1.2.5 \
            pytest-embedded-serial-esp==1.2.5 \
            pytest-embedded-idf==1.2.5 \
            pytest-embedded-qemu==1.2.5

    - name: Patch esp-idf to fix race condition
      run: |
        set -e
        PATCH=$PWD/esp_ipc_isr.patch
        cd $IDF_PATH
        patch -p1 < $PATCH

    - name: Build using idf.py
      run: |
        set -e
        . $IDF_PATH/export.sh
        idf.py build

    - name: Run test using qemu
      timeout-minutes: 10
      run: |
        set -e
        . $IDF_PATH/export.sh
        pytest --embedded-services=idf,qemu -s
