name: ESP32 Test

on: [push, workflow_dispatch]

jobs:
  esp32-test:
    runs-on: ubuntu-latest
    container: espressif/idf:v4.4.4

    strategy:
      fail-fast: false
      matrix:
        flappiness: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F"]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies to run qemu
      run: |
        set -eu
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y -q \
            libglib2.0-0 libpixman-1-0 libslirp0

    - name: Install qemu binary from espressif/qemu
      run: |
        set -eu
        QEMU_VER=esp-develop-7.2.0-20230223
        QEMU_DIST=esp-qemu-xtensa-softmmu-develop_7.2.0_20230223-x86_64-linux-gnu.tar.bz2
        QEMU_SHA256=7ac441ddbc0435350cc02266ede63fb5d3da37acc70ae61c293c7c3c9ba4636f
        wget --no-verbose https://github.com/espressif/qemu/releases/download/${QEMU_VER}/${QEMU_DIST}
        echo "${QEMU_SHA256} *${QEMU_DIST}" | sha256sum --check --strict -
        tar -xf ${QEMU_DIST} -C /opt

    - name: Install pytest and pytest-embedded plugins
      run: |
        set -e
        . $IDF_PATH/export.sh
        pip install pytest==7.0.1 \
            pytest-embedded==1.2.5 \
            pytest-embedded-serial-esp==1.2.5 \
            pytest-embedded-idf==1.2.5 \
            pytest-embedded-qemu==1.2.5

    - name: Build using idf.py
      run: |
        set -e
        . $IDF_PATH/export.sh
        idf.py build

    - name: Run test using qemu
      timeout-minutes: 10
      run: |
        set -e
        . $IDF_PATH/export.sh
        export PATH=/opt/qemu/bin:${PATH}
        pytest --embedded-services=idf,qemu --erase-nvs=y -s
